### ISSUE TITLE
Update POI version or remove this as a dep?

### ISSUE THREAD

**Issue by kjordan2001** [cuba-platform/apache-poi#1]
Is this necessary as a dependency for YARG anymore?  The version this has is somewhat old and if you're pulling in newer versions of POI, there are some differences (such as Workbook now implementing Closeable) that if this dep gets pulled in and gets first in line, then you can get mysterious compile errors about methods missing and such.  So can this either get updated or removed as a YARG dep and the official versions added as a dep?

**Comment by tinhol** [comment]
Hello.

In the forked POI we have done some significant fixes, required for YARG.

But, you are right, we have to update the dependency or get rid of it by using mainstream version.

We will schedule the activity with high priority.

Thank you for your feedback.

**Comment by kjordan2001** [comment]
Is this being looked into?  It's still using a 3+ year old version of POI.

**Comment by jreznot** [comment]
Hi, it is already done! See YARG build.gradle: https://github.com/cuba-platform/yarg/blob/master/core/build.gradle

YARG 1.1 will be included to CUBA 6.4. It uses original POI 3.15
